FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install make
RUN apt-get -y install python2.7
RUN apt-get -y install python-pip

RUN ln -fs /usr/bin/python2.7 /usr/bin/python2
RUN python2 -m pip install nose coverage requests
COPY . /opt/brat

WORKDIR /opt/brat

CMD ["make", "tests2"]