FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install make
RUN apt-get -y install python3.6
RUN apt-get -y install python3-pip

RUN ln -fs /usr/bin/python3.6 /usr/bin/python3


COPY . /opt/arat
WORKDIR /opt/arat

RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install -r requirements_test.txt


CMD ["make", "tests3"]