FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install make
RUN apt-get -y install python2.7
RUN apt-get -y install python-pip

RUN ln -fs /usr/bin/python2.7 /usr/bin/python2

COPY . /opt/arat
WORKDIR /opt/arat

RUN python2 -m pip install -r requirements.txt
RUN python2 -m pip install -r requirements_test.txt nose nose-timer


CMD ["make", "tests2"]